## Logistic Regression

In [ ]:
# null hypothesis: all coefficients in the model are equal to zero 
# (predictor variables have a statistically significant relationship with y)
# alternative hypothesis: not every coefficient is equal to zero

# we are using 21 predictors

In [70]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder,RobustScaler,PowerTransformer
from sklearn.preprocessing import KBinsDiscretizer,Binarizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression,SGDClassifier,SGDRegressor
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import pymongo
import pandas as pd
import numpy as np
from collections import Counter
from config import db_password

In [76]:
client = pymongo.MongoClient(f"mongodb+srv://nickj:{db_password}@capstonecluster.7h9ij.mongodb.net/CapstoneCluster?retryWrites=true&w=majority")

db = client.listings_db
collection1 = db.X_set.find()

collection2 = db.y_set.find()

In [77]:
X = pd.DataFrame(collection1)
y = pd.DataFrame(collection2)

In [78]:
X = X.drop('_id',1)
X['price'] = X['price'].div(100)
X['amenities'] = X['amenities'].div(100)
X['maximum_nights'] = X['maximum_nights'].div(100)
y_new = []
for i in y['is_success'][0]:
    if i == 'yes':
        y_new.append(1)
    else:
        y_new.append(0)
        
y = y_new

/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [79]:
X['is_success']=y
 
X.head()

host_identity_verified  accommodates  bathrooms  bedrooms  beds  bed_type  \
0                       1             3        1.0       1.0   3.0         4   
1                       1             4        1.0       1.0   3.0         4   
2                       1             2        1.0       0.0   1.0         4   
3                       1             4        1.0       1.0   1.0         4   
4                       1             2        1.0       1.0   1.0         4   

   amenities  price  security_deposit  cleaning_fee  ...  minimum_nights  \
0       0.32   0.59               0.0          0.60  ...               2   
1       0.44   1.49               1.0          0.25  ...               1   
2       0.36   2.25               3.5          1.00  ...               1   
3       0.12   0.89               3.0          0.60  ...               1   
4       0.25   0.70               1.5          1.25  ...               5   

   maximum_nights  instant_bookable  is_business_travel_ready  \
0            0.21                 0                         0   
1            7.30                 0                         0   
2           11.25                 0                         0   
3            7.30                 0                         0   
4            7.30                 0                         0   

   cancellation_policy  require_guest_profile_picture  \
0                    3                              0   
1                    4                              0   
2                    3                              1   
3                    3                              0   
4                    3                              0   

   require_guest_phone_verification  neighbourhood  room  is_success  
0                                 0              4     1           0  
1                                 0              3     1           1  
2                                 1              4     2           1  
3                                 0              3     1           0  
4                                 0              3     1           1  

[5 rows x 22 columns]

In [80]:
X = X.sort_values(by=['maximum_nights'],ascending=False)[3:]

In [81]:
X.head()

host_identity_verified  accommodates  bathrooms  bedrooms  beds  \
2459                       1             3        1.0       1.0   1.0   
1902                       1             2        1.0       1.0   1.0   
8412                       0             6        1.0       2.0   3.0   
6136                       0             6        1.0       2.0   4.0   
6686                       1             3        1.0       1.0   3.0   

      bed_type  amenities  price  security_deposit  cleaning_fee  ...  \
2459         4       0.27   1.72               2.0          0.75  ...   
1902         4       0.09   1.20              50.0          0.00  ...   
8412         4       0.12   1.85               2.5          1.45  ...   
6136         4       0.40   1.11               0.0          0.65  ...   
6686         4       0.40   0.69               0.0          0.29  ...   

      minimum_nights  maximum_nights  instant_bookable  \
2459               1          999.99                 1   
1902               5          600.00                 0   
8412               2           99.99                 0   
6136               2           50.00                 0   
6686               2           41.25                 0   

      is_business_travel_ready  cancellation_policy  \
2459                         0                    4   
1902                         0                    3   
8412                         0                    3   
6136                         0                    3   
6686                         0                    5   

      require_guest_profile_picture  require_guest_phone_verification  \
2459                              0                                 0   
1902                              0                                 0   
8412                              0                                 0   
6136                              0                                 0   
6686                              0                                 0   

      neighbourhood  room  is_success  
2459              3     2           0  
1902              4     1           1  
8412              3     2           0  
6136              3     2           1  
6686              2     1           1  

[5 rows x 22 columns]

In [82]:
# there seem to be some outliers in some columns in continuous variables
cont = X[['accommodates', 'bathrooms', 'bedrooms',
       'beds', 'amenities', 'price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights']]
cont.describe()

accommodates     bathrooms      bedrooms          beds     amenities  \
count  15960.000000  15960.000000  15960.000000  15960.000000  15960.000000   
mean       3.305388      1.170990      1.273810      1.796554      0.240799   
std        2.172312      0.505956      0.840775      1.294196      0.098599   
min        1.000000      0.000000      0.000000      0.000000      0.010000   
25%        2.000000      1.000000      1.000000      1.000000      0.170000   
50%        2.000000      1.000000      1.000000      1.000000      0.230000   
75%        4.000000      1.000000      1.000000      2.000000      0.300000   
max       16.000000     16.500000     14.000000     40.000000      0.820000   

              price  security_deposit  cleaning_fee  guests_included  \
count  15960.000000      15960.000000  15960.000000     15960.000000   
mean       1.546612          2.548427      0.694052         1.803133   
std        1.781979          4.475486      0.562435         1.390159   
min        0.000000          0.000000      0.000000         1.000000   
25%        0.720000          0.000000      0.300000         1.000000   
50%        1.160000          1.250000      0.600000         1.000000   
75%        1.850000          3.000000      1.000000         2.000000   
max       85.000000         51.000000      6.000000        16.000000   

       extra_people  minimum_nights  maximum_nights  
count  15960.000000    15960.000000    15960.000000  
mean       0.201096        5.909586        5.735107  
std        0.254423       15.275039       10.620205  
min        0.000000        1.000000        0.010000  
25%        0.000000        1.000000        0.300000  
50%        0.150000        2.000000        3.650000  
75%        0.250000        4.000000       11.250000  
max        3.000000     1100.000000      999.990000

In [83]:
y = X['is_success']
X = X.drop('is_success',1)

/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  


In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)

In [85]:
X_train.shape

(14364, 21)

In [86]:
X_test.shape

(1596, 21)

In [87]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_ss = X_scaler.transform(X_train)
test_ss = X_scaler.transform(X_test)

In [88]:
# Scaled data has zero mean and unit variance:
X_ss.mean(axis=0),X_ss.std(axis=0)

(array([-1.90200280e-16, -4.67462326e-17,  2.10234379e-17,  2.67121329e-17,
         2.37441182e-17,  2.87897433e-16, -4.45202215e-16,  4.25415450e-17,
        -4.40255524e-17,  1.85006254e-16,  1.87974269e-17, -1.03633182e-16,
        -9.89338256e-18, -8.75564357e-17, -3.19061588e-17,  0.00000000e+00,
        -3.46268390e-17,  8.60724283e-17,  6.72750014e-17,  2.63658645e-16,
        -1.73628864e-16]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        1., 1., 1., 1.]))

In [89]:
# Scale features using statistics that are robust to outliers.

# This Scaler removes the median and scales the data according to the quantile range 
# (defaults to IQR: Interquartile Range). The IQR is the range between the 1st 
# quartile (25th quantile) and the 3rd quartile (75th quantile).

# Centering and scaling happen independently on each feature by computing the relevant 
# statistics on the samples in the training set. Median and interquartile range are then 
# stored to be used on later data using the transform method.

# Standardization of a dataset is a common requirement for many machine learning estimators. 
# Typically this is done by removing the mean and scaling to unit variance. However, outliers 
# can often influence the sample mean / variance in a negative way. In such cases, the median 
# and the interquartile range often give better results.

In [90]:
transformer = RobustScaler().fit(X_train)
transformer

train_Ro = transformer.transform(X_train)
test_Ro = transformer.transform(X_test)

In [91]:
# Scaled data mean and variance
train_Ro.mean(axis=0),test_Ro.std(axis=0)

(array([-0.4796714 ,  0.65159426,  0.17091339,  0.27464495,  0.79727096,
        -0.03411306,  0.08689459,  0.3485804 ,  0.4342465 ,  0.13395393,
         0.79741019,  0.20451685,  1.32075559,  0.19180015,  0.39452799,
         0.        ,  0.53933445,  0.03808131,  0.03968254,  0.25160123,
        -0.44075466]),
 array([0.49987279, 1.09611894, 0.51722213, 0.79465099, 1.20428526,
        0.26666935, 0.75514161, 1.32718865, 1.5124836 , 0.83940956,
        1.54227716, 0.95242779, 3.09838615, 0.48238698, 0.49047746,
        0.        , 0.73230793, 0.18868182, 0.18868182, 0.8565619 ,
        0.53441194]))

In [92]:
bin = Binarizer()

train_bin = bin.fit_transform(X_train)
test_bin = bin.fit_transform(X_test)

In [93]:
train_bin

array([[0., 1., 1., ..., 0., 1., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 1.],
       ...,
       [0., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [0., 1., 1., ..., 0., 1., 1.]])

In [94]:
# Scaled data mean and variance:
train_bin.mean(axis=0),train_bin.std(axis=0)

(array([0.5203286 , 1.        , 0.99839877, 0.91033138, 0.99227235,
        0.99895572, 1.        , 0.9992342 , 0.64174325, 0.93964077,
        1.        , 0.65559733, 1.        , 1.        , 0.39452799,
        0.        , 0.99993038, 0.03808131, 0.03968254, 0.98948761,
        0.98085492]),
 array([0.49958658, 0.        , 0.03998326, 0.28570641, 0.08756675,
        0.0322984 , 0.        , 0.02766255, 0.47948811, 0.2381512 ,
        0.        , 0.4751731 , 0.        , 0.        , 0.48874907,
        0.        , 0.00834348, 0.1913926 , 0.19521228, 0.10198962,
        0.13703485]))

In [95]:
clf = SGDClassifier(loss="log", max_iter=300).fit(train_bin,y_train)
predictions = clf.predict(test_ss)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            4          298
Actual 1            8         1286

Accuracy Score : 0.8082706766917294
Classification Report
              precision    recall  f1-score   support

           0       0.33      0.01      0.03       302
           1       0.81      0.99      0.89      1294

    accuracy                           0.81      1596
   macro avg       0.57      0.50      0.46      1596
weighted avg       0.72      0.81      0.73      1596



In [ ]:
# the gradient of the loss is estimated each sample at a time and the model is updated along the way with 
# a decreasing strength schedule (aka learning rate).

# Linear classifiers (SVM, logistic regression, etc.) with SGD training.

# The ‘log’ loss gives logistic regression, a probabilistic classifier. 

# For best results using the default learning rate schedule, the data should have zero mean and unit variance.

# The “sag” solver uses Stochastic Average Gradient descent 6. It is faster than other solvers for large datasets, 
# when both the number of samples and the number of features are large.
# ‘sag’ and ‘saga’ fast convergence is only guaranteed on features with approximately the same scale.

# The regularizer is a penalty added to the loss function that shrinks model parameters towards the zero vector.

# The classes SGDClassifier and SGDRegressor provide functionality to fit linear models for classification and 
# regression using different (convex) loss functions and different penalties. E.g., with loss="log", SGDClassifier 
# fits a logistic regression model, while with loss="hinge" it fits a linear support vector machine (SVM).


# The class SGDRegressor implements a plain stochastic gradient descent learning routine which supports different 
# loss functions and penalties to fit linear regression models. SGDRegressor is well suited for regression problems 
# with a large number of training samples (> 10.000), for other problems we recommend Ridge, Lasso, or ElasticNet.

In [ ]:

# Given a set of training examples where and (for classification), 
# our goal is to learn a linear scoring function with model parameters 
# and intercept . In order to make predictions for binary classification, 
# we simply look at the sign of . To find the model parameters, we minimize 
# the regularized training error given by



# where L is a loss function that measures model (mis)fit and  is a regularization term (aka penalty) that
# penalizes model complexity; alpha > 0 is a non-negative hyperparameter that controls the regularization strength.
# Log: equivalent to Logistic Regression.



In [ ]:
LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, 
                   class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, 
                   warm_start=False, n_jobs=None, l1_ratio=None)

In [ ]:
SGDClassifier(loss='hinge', *, penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, 
              tol=0.001, shuffle=True, verbose=0, epsilon=0.1, n_jobs=None, random_state=None, 
              learning_rate='optimal', eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, 
              n_iter_no_change=5, class_weight=None, warm_start=False, average=False)

In [ ]:
SGDRegressor(loss='squared_error', *, penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, 
             max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, random_state=None, 
             learning_rate='invscaling', eta0=0.01, power_t=0.25, early_stopping=False, validation_fraction=0.1, 
             n_iter_no_change=5, warm_start=False, average=False)

In [110]:
import pandas as pd
from path import Path
from sklearn.preprocessing import RobustScaler,Binarizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

## Random Forest with Binarizer()

In [126]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)

# Creating a StandardScaler instance.
scaler = Binarizer()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=0) 

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            9          293
Actual 1            3         1291

Accuracy Score : 0.8145363408521303
Classification Report
              precision    recall  f1-score   support

           0       0.75      0.03      0.06       302
           1       0.82      1.00      0.90      1294

    accuracy                           0.81      1596
   macro avg       0.78      0.51      0.48      1596
weighted avg       0.80      0.81      0.74      1596



In [117]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_

# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.2082498415115371, 'instant_bookable'),
 (0.14563061825558948, 'host_identity_verified'),
 (0.11357445362441397, 'extra_people'),
 (0.09630540600636277, 'security_deposit'),
 (0.0712107278441215, 'cleaning_fee'),
 (0.06657460338065607, 'require_guest_phone_verification'),
 (0.06425616793236923, 'bedrooms'),
 (0.06147492329862924, 'room'),
 (0.05715024800077582, 'require_guest_profile_picture'),
 (0.04333130852913801, 'beds'),
 (0.030283471079919244, 'neighbourhood'),
 (0.016277831848289907, 'bathrooms'),
 (0.013364477291118074, 'bed_type'),
 (0.01192000674963221, 'price'),
 (0.0003959146474474704, 'cancellation_policy'),
 (0.0, 'minimum_nights'),
 (0.0, 'maximum_nights'),
 (0.0, 'is_business_travel_ready'),
 (0.0, 'guests_included'),
 (0.0, 'amenities'),
 (0.0, 'accommodates')]

In [128]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)

transformer = RobustScaler().fit(X_train)


# Scaling the data.
X_train_scaled = transformer.transform(X_train)
X_test_scaled = transformer.transform(X_test)

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=0) 

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0           50          252
Actual 1           32         1262

Accuracy Score : 0.8220551378446115
Classification Report
              precision    recall  f1-score   support

           0       0.61      0.17      0.26       302
           1       0.83      0.98      0.90      1294

    accuracy                           0.82      1596
   macro avg       0.72      0.57      0.58      1596
weighted avg       0.79      0.82      0.78      1596



## Logistic Regression with RobustScalar

In [127]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)


# Fitting the Standard Scaler with the training data.
transformer = RobustScaler().fit(X_train)

# Scaling the data.
X_train_scaled = transformer.transform(X_train)
X_test_scaled = transformer.transform(X_test)

# Create a random forest classifier.
lgRo = LogisticRegression(penalty='l2',solver='sag',max_iter=300,random_state=0)

# Fitting the model
lgRo = lgRo.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = lgRo.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,


Predicted 0  Predicted 1
Actual 0            6          296
Actual 1            3         1291

Accuracy Score : 0.8126566416040101
Classification Report
              precision    recall  f1-score   support

           0       0.67      0.02      0.04       302
           1       0.81      1.00      0.90      1294

    accuracy                           0.81      1596
   macro avg       0.74      0.51      0.47      1596
weighted avg       0.79      0.81      0.73      1596



In [129]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)


# Creating a StandardScaler instance.
scaler = Binarizer()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)


# Create a random forest classifier.
lgB = LogisticRegression(penalty='l2',solver='sag',max_iter=300,random_state=0)

# Fitting the model
lgB = lgB.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = lgB.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,


Predicted 0  Predicted 1
Actual 0            6          296
Actual 1            3         1291

Accuracy Score : 0.8126566416040101
Classification Report
              precision    recall  f1-score   support

           0       0.67      0.02      0.04       302
           1       0.81      1.00      0.90      1294

    accuracy                           0.81      1596
   macro avg       0.74      0.51      0.47      1596
weighted avg       0.79      0.81      0.73      1596

