In [ ]:
# null hypothesis: all coefficients in the model are equal to zero 
# (predictor variables have a statistically significant relationship with y)
# alternative hypothesis: not every coefficient is equal to zero

# we are using 21 predictors

In [1]:
#Dependencies
from sklearn.preprocessing import StandardScaler,OneHotEncoder,RobustScaler,PowerTransformer
from sklearn.preprocessing import KBinsDiscretizer,Binarizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression,SGDClassifier,SGDRegressor
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import pymongo
import pandas as pd
import numpy as np
from collections import Counter
from config import db_password

In [137]:
client = pymongo.MongoClient(f"mongodb+srv://nickj:{db_password}@capstonecluster.7h9ij.mongodb.net/CapstoneCluster?retryWrites=true&w=majority")

db = client.listings_db
collection1 = db.X_set.find()

collection2 = db.y_set.find()

X = pd.DataFrame(collection1)
y = pd.DataFrame(collection2)

X = X.drop('_id',1)
X['price'] = X['price'].div(100)
X['amenities'] = X['amenities'].div(10)
X['maximum_nights'] = X['maximum_nights'].div(100)
y_new = []
for i in y['is_success'][0]:
    if i == 'yes':
        y_new.append(1)
    else:
        y_new.append(0)
        
y = y_new

X['is_success']=y

X = X.sort_values(by=['maximum_nights'],ascending=False)[3:]

y = X['is_success']
X = X.drop('is_success',1)

/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  # This is added back by InteractiveShellApp.init_path()
/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:29: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only


In [127]:
# there seem to be some outliers in some columns in continuous variables
cont = X[['accommodates', 'bathrooms', 'bedrooms',
       'beds', 'amenities', 'price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights']]
cont.describe()

accommodates     bathrooms      bedrooms          beds     amenities  \
count  15960.000000  15960.000000  15960.000000  15960.000000  15960.000000   
mean       3.305388      1.170990      1.273810      1.796554      0.240799   
std        2.172312      0.505956      0.840775      1.294196      0.098599   
min        1.000000      0.000000      0.000000      0.000000      0.010000   
25%        2.000000      1.000000      1.000000      1.000000      0.170000   
50%        2.000000      1.000000      1.000000      1.000000      0.230000   
75%        4.000000      1.000000      1.000000      2.000000      0.300000   
max       16.000000     16.500000     14.000000     40.000000      0.820000   

              price  security_deposit  cleaning_fee  guests_included  \
count  15960.000000      15960.000000  15960.000000     15960.000000   
mean       1.546612          2.548427      0.694052         1.803133   
std        1.781979          4.475486      0.562435         1.390159   
min        0.000000          0.000000      0.000000         1.000000   
25%        0.720000          0.000000      0.300000         1.000000   
50%        1.160000          1.250000      0.600000         1.000000   
75%        1.850000          3.000000      1.000000         2.000000   
max       85.000000         51.000000      6.000000        16.000000   

       extra_people  minimum_nights  maximum_nights  
count  15960.000000    15960.000000    15960.000000  
mean       0.201096        5.909586        5.735107  
std        0.254423       15.275039       10.620205  
min        0.000000        1.000000        0.010000  
25%        0.000000        1.000000        0.300000  
50%        0.150000        2.000000        3.650000  
75%        0.250000        4.000000       11.250000  
max        3.000000     1100.000000      999.990000

## Splitting Data into Training and Testing Sets

In [138]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)

X_train.shape

(14364, 21)

## Testing Different Scalers

### Scaled data has zero mean and unit variance:

In [129]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_ss = X_scaler.transform(X_train)
test_ss = X_scaler.transform(X_test)

In [130]:
# Scaled data mean and variance
X_ss.mean(axis=0),X_ss.std(axis=0)

(array([-1.90200280e-16, -4.67462326e-17,  2.10234379e-17,  2.67121329e-17,
         2.37441182e-17,  2.87897433e-16, -4.45202215e-16,  4.25415450e-17,
        -4.40255524e-17,  1.85006254e-16,  1.87974269e-17, -1.03633182e-16,
        -9.89338256e-18, -8.75564357e-17, -3.19061588e-17,  0.00000000e+00,
        -3.46268390e-17,  8.60724283e-17,  6.72750014e-17,  2.63658645e-16,
        -1.73628864e-16]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
        1., 1., 1., 1.]))

In [131]:
# RobustScaler
transformer = RobustScaler().fit(X_train)
transformer

train_Ro = transformer.transform(X_train)
test_Ro = transformer.transform(X_test)

In [132]:
# Scaled data mean and variance
train_Ro.mean(axis=0),test_Ro.std(axis=0)

(array([-0.4796714 ,  0.65159426,  0.17091339,  0.27464495,  0.79727096,
        -0.03411306,  0.08689459,  0.3485804 ,  0.4342465 ,  0.13395393,
         0.79741019,  0.20451685,  1.32075559,  0.19180015,  0.39452799,
         0.        ,  0.53933445,  0.03808131,  0.03968254,  0.25160123,
        -0.44075466]),
 array([0.49987279, 1.09611894, 0.51722213, 0.79465099, 1.20428526,
        0.26666935, 0.75514161, 1.32718865, 1.5124836 , 0.83940956,
        1.54227716, 0.95242779, 3.09838615, 0.48238698, 0.49047746,
        0.        , 0.73230793, 0.18868182, 0.18868182, 0.8565619 ,
        0.53441194]))

In [133]:
# bins into 1s and 0s default threshold=0.0
bin = Binarizer()

train_bin = bin.fit_transform(X_train)
test_bin = bin.fit_transform(X_test)

train_bin

array([[0., 1., 1., ..., 0., 1., 1.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 1.],
       ...,
       [0., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 1.],
       [0., 1., 1., ..., 0., 1., 1.]])

In [134]:
# Scaled data mean and variance:
train_bin.mean(axis=0),train_bin.std(axis=0)

(array([0.5203286 , 1.        , 0.99839877, 0.91033138, 0.99227235,
        0.99895572, 1.        , 0.9992342 , 0.64174325, 0.93964077,
        1.        , 0.65559733, 1.        , 1.        , 0.39452799,
        0.        , 0.99993038, 0.03808131, 0.03968254, 0.98948761,
        0.98085492]),
 array([0.49958658, 0.        , 0.03998326, 0.28570641, 0.08756675,
        0.0322984 , 0.        , 0.02766255, 0.47948811, 0.2381512 ,
        0.        , 0.4751731 , 0.        , 0.        , 0.48874907,
        0.        , 0.00834348, 0.1913926 , 0.19521228, 0.10198962,
        0.13703485]))

In [135]:
#Dependencies
import pandas as pd
from path import Path
from sklearn.preprocessing import RobustScaler,Binarizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import balanced_accuracy_score
from imblearn.metrics import classification_report_imbalanced

## Logistic Regression with RobustScalar

In [141]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)


# Fitting the Standard Scaler with the training data.
transformer = RobustScaler().fit(X_train)

# Scaling the data.
X_train_scaled = transformer.transform(X_train)
X_test_scaled = transformer.transform(X_test)

# Create a random forest classifier.
lgRo = LogisticRegression(solver='lbfgs', random_state=1)

# Fitting the model
lgRo = lgRo.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = lgRo.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            9          293
Actual 1            6         1288

Accuracy Score : 0.8126566416040101
Classification Report
              precision    recall  f1-score   support

           0       0.60      0.03      0.06       302
           1       0.81      1.00      0.90      1294

    accuracy                           0.81      1596
   macro avg       0.71      0.51      0.48      1596
weighted avg       0.77      0.81      0.74      1596



## Random Forest with Binarizer()

In [ ]:
# the results for this model were not impressive

In [111]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)

# Creating a StandardScaler instance.
scaler = Binarizer()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=0) 

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_

# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

Confusion Matrix


Predicted 0  Predicted 1
Actual 0            9          293
Actual 1            3         1291

Accuracy Score : 0.8145363408521303
Classification Report
              precision    recall  f1-score   support

           0       0.75      0.03      0.06       302
           1       0.82      1.00      0.90      1294

    accuracy                           0.81      1596
   macro avg       0.78      0.51      0.48      1596
weighted avg       0.80      0.81      0.74      1596



[(0.2082498415115371, 'instant_bookable'),
 (0.14563061825558948, 'host_identity_verified'),
 (0.11357445362441397, 'extra_people'),
 (0.09630540600636277, 'security_deposit'),
 (0.0712107278441215, 'cleaning_fee'),
 (0.06657460338065607, 'require_guest_phone_verification'),
 (0.06425616793236923, 'bedrooms'),
 (0.06147492329862924, 'room'),
 (0.05715024800077582, 'require_guest_profile_picture'),
 (0.04333130852913801, 'beds'),
 (0.030283471079919244, 'neighbourhood'),
 (0.016277831848289907, 'bathrooms'),
 (0.013364477291118074, 'bed_type'),
 (0.01192000674963221, 'price'),
 (0.0003959146474474704, 'cancellation_policy'),
 (0.0, 'minimum_nights'),
 (0.0, 'maximum_nights'),
 (0.0, 'is_business_travel_ready'),
 (0.0, 'guests_included'),
 (0.0, 'amenities'),
 (0.0, 'accommodates')]

## RandomForestClassifier with RobustScaler()

In [ ]:
# this model has given the best results so far

In [115]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=0)

transformer = RobustScaler().fit(X_train)


# Scaling the data.
X_train_scaled = transformer.transform(X_train)
X_test_scaled = transformer.transform(X_test)

# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=0) 

# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)

# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_

# We can sort the features by their importance.
print(f"Feature Importance : ")

sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

Confusion Matrix


Predicted 0  Predicted 1
Actual 0           50          252
Actual 1           32         1262

Accuracy Score : 0.8220551378446115
Classification Report
              precision    recall  f1-score   support

           0       0.61      0.17      0.26       302
           1       0.83      0.98      0.90      1294

    accuracy                           0.82      1596
   macro avg       0.72      0.57      0.58      1596
weighted avg       0.79      0.82      0.78      1596

Feature Importance : 


[(0.14166282747357758, 'price'),
 (0.1310220998036831, 'amenities'),
 (0.10560037283436863, 'cleaning_fee'),
 (0.07788882462537369, 'maximum_nights'),
 (0.07399494176421915, 'extra_people'),
 (0.07313297725909008, 'minimum_nights'),
 (0.07141977963949586, 'security_deposit'),
 (0.0564625368165704, 'accommodates'),
 (0.038320898567455915, 'beds'),
 (0.03684102672923589, 'neighbourhood'),
 (0.035931274295566876, 'guests_included'),
 (0.02925441692359164, 'bedrooms'),
 (0.028693131728479225, 'cancellation_policy'),
 (0.025108370596539736, 'bathrooms'),
 (0.021786412976933536, 'host_identity_verified'),
 (0.01909101294544024, 'instant_bookable'),
 (0.015267973140351372, 'room'),
 (0.006506151742154061, 'require_guest_phone_verification'),
 (0.006085536424883748, 'bed_type'),
 (0.005929433712989231, 'require_guest_profile_picture'),
 (0.0, 'is_business_travel_ready')]

## Setting training and test sets for more trials

In [95]:
X_train, X_test, y_train, y_test = train_test_split(X,
   y,  test_size=0.1, random_state=1)

transformer = RobustScaler().fit(X_train)
#transformer = StandardScaler().fit(X_train)

X_train_scaled = transformer.transform(X_train)
X_test_scaled = transformer.transform(X_test)

Counter(y_train)

Counter({1: 11633, 0: 2731})

## Oversampling (LogisticRegression)

In [ ]:
## This model increased the precision for 1 but 0 is still not great

In [143]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)

model = LogisticRegression(solver='lbfgs', random_state=1).fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

print("Confusion Matrix")
display(cm_df)

print(balanced_accuracy_score(y_test, y_pred))

print(classification_report_imbalanced(y_test, y_pred))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0          196          106
Actual 1          517          777

0.6247351505163925
                   pre       rec       spe        f1       geo       iba       sup

          0       0.27      0.65      0.60      0.39      0.62      0.39       302
          1       0.88      0.60      0.65      0.71      0.62      0.39      1294

avg / total       0.77      0.61      0.64      0.65      0.62      0.39      1596



## SMOTE (LogisticRegression)

In [144]:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,
sampling_strategy='auto').fit_resample(
   X_train_scaled, y_train)

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
confusion_matrix(y_test, y_pred)

print(balanced_accuracy_score(y_test, y_pred))


y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

print(confusion_matrix(y_test, y_pred))

print(classification_report_imbalanced(y_test, y_pred))

0.6182226680450782
[[170 132]
 [575 719]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.23      0.56      0.56      0.32      0.56      0.31       302
          1       0.84      0.56      0.56      0.67      0.56      0.31      1294

avg / total       0.73      0.56      0.56      0.60      0.56      0.31      1596



/Users/annasand/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/base.py:439: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


## UnderSampling (LogisticRegression)

In [145]:
from imblearn.under_sampling import RandomUnderSampler
ros = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)

model = LogisticRegression(solver='lbfgs', random_state=1).fit(X_resampled, y_resampled)
y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))

print(balanced_accuracy_score(y_test, y_pred))
print(classification_report_imbalanced(y_test, y_pred))

[[194 108]
 [504 790]]
0.6264470761640583
                   pre       rec       spe        f1       geo       iba       sup

          0       0.28      0.64      0.61      0.39      0.63      0.39       302
          1       0.88      0.61      0.64      0.72      0.63      0.39      1294

avg / total       0.77      0.62      0.64      0.66      0.63      0.39      1596



## Cluster Centroid Undersampling (LogisticRegression)

In [146]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train_scaled, y_train)

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))
print(balanced_accuracy_score(y_test, y_pred))
print(classification_report_imbalanced(y_test, y_pred))

[[229  73]
 [766 528]]
0.5831576199883313
                   pre       rec       spe        f1       geo       iba       sup

          0       0.23      0.76      0.41      0.35      0.56      0.32       302
          1       0.88      0.41      0.76      0.56      0.56      0.30      1294

avg / total       0.76      0.47      0.69      0.52      0.56      0.30      1596



## SMOTEEN (Logistic Regression)

In [148]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X_train_scaled, y_train)

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))
print(balanced_accuracy_score(y_test, y_pred))
print(classification_report_imbalanced(y_test, y_pred))

[[257  45]
 [882 412]]
0.584692979313592
                   pre       rec       spe        f1       geo       iba       sup

          0       0.23      0.85      0.32      0.36      0.52      0.29       302
          1       0.90      0.32      0.85      0.47      0.52      0.26      1294

avg / total       0.77      0.42      0.75      0.45      0.52      0.26      1596



## Oversampling (RFC)

In [149]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)


model = RandomForestClassifier(n_estimators=128, random_state=0).fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
cm = confusion_matrix(y_test, y_pred)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

print("Confusion Matrix")
display(cm_df)

print(balanced_accuracy_score(y_test, y_pred))

print(classification_report_imbalanced(y_test, y_pred))

Confusion Matrix


Predicted 0  Predicted 1
Actual 0           73          229
Actual 1           66         1228

0.5953586087597367
                   pre       rec       spe        f1       geo       iba       sup

          0       0.53      0.24      0.95      0.33      0.48      0.21       302
          1       0.84      0.95      0.24      0.89      0.48      0.25      1294

avg / total       0.78      0.82      0.38      0.79      0.48      0.24      1596



## SMOTE (RFC)

In [150]:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=1,
sampling_strategy='auto').fit_resample(
   X_train_scaled, y_train)

model =  RandomForestClassifier(n_estimators=128, random_state=0).fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
confusion_matrix(y_test, y_pred)

print(balanced_accuracy_score(y_test, y_pred))


y_pred = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

print(confusion_matrix(y_test, y_pred))

print(classification_report_imbalanced(y_test, y_pred))

0.5976207048322876
[[  76  226]
 [  73 1221]]
                   pre       rec       spe        f1       geo       iba       sup

          0       0.51      0.25      0.94      0.34      0.49      0.22       302
          1       0.84      0.94      0.25      0.89      0.49      0.25      1294

avg / total       0.78      0.81      0.38      0.79      0.49      0.25      1596



## UnderSampling (RFC)

In [151]:
from imblearn.under_sampling import RandomUnderSampler
ros = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train_scaled, y_train)

model = RandomForestClassifier(n_estimators=128, random_state=0).fit(X_resampled, y_resampled)
y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))

print(balanced_accuracy_score(y_test, y_pred))
print(classification_report_imbalanced(y_test, y_pred))

[[194 108]
 [436 858]]
0.6527221920836873
                   pre       rec       spe        f1       geo       iba       sup

          0       0.31      0.64      0.66      0.42      0.65      0.43       302
          1       0.89      0.66      0.64      0.76      0.65      0.43      1294

avg / total       0.78      0.66      0.65      0.69      0.65      0.43      1596



## Clusters (RFC)

In [152]:
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train_scaled, y_train)

model = RandomForestClassifier(n_estimators=128, random_state=0)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))
print(balanced_accuracy_score(y_test, y_pred))
print(classification_report_imbalanced(y_test, y_pred))

[[ 260   42]
 [1060  234]]
0.5208808868235463
                   pre       rec       spe        f1       geo       iba       sup

          0       0.20      0.86      0.18      0.32      0.39      0.17       302
          1       0.85      0.18      0.86      0.30      0.39      0.15      1294

avg / total       0.72      0.31      0.73      0.30      0.39      0.15      1596



## SMOTEEN (RFC)

In [153]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X_train_scaled, y_train)

model = RandomForestClassifier(n_estimators=128, random_state=0)
model.fit(X_resampled, y_resampled)

y_pred = model.predict(X_test_scaled)
print(confusion_matrix(y_test, y_pred))
print(balanced_accuracy_score(y_test, y_pred))
print(classification_report_imbalanced(y_test, y_pred))

[[154 148]
 [304 990]]
0.6375016633059357
                   pre       rec       spe        f1       geo       iba       sup

          0       0.34      0.51      0.77      0.41      0.62      0.38       302
          1       0.87      0.77      0.51      0.81      0.62      0.40      1294

avg / total       0.77      0.72      0.56      0.74      0.62      0.40      1596



## scikit-learn Documentation

In [ ]:
#https://scikit-learn.org/stable/

# the gradient of the loss is estimated each sample at a time and the model is updated along the way with 
# a decreasing strength schedule (aka learning rate).

# Linear classifiers (SVM, logistic regression, etc.) with SGD training.

# The ‘log’ loss gives logistic regression, a probabilistic classifier. 

# For best results using the default learning rate schedule, the data should have zero mean and unit variance.

# The “sag” solver uses Stochastic Average Gradient descent 6. It is faster than other solvers for large datasets, 
# when both the number of samples and the number of features are large.
# ‘sag’ and ‘saga’ fast convergence is only guaranteed on features with approximately the same scale.

# The regularizer is a penalty added to the loss function that shrinks model parameters towards the zero vector.

# The classes SGDClassifier and SGDRegressor provide functionality to fit linear models for classification and 
# regression using different (convex) loss functions and different penalties. E.g., with loss="log", SGDClassifier 
# fits a logistic regression model, while with loss="hinge" it fits a linear support vector machine (SVM).


# The class SGDRegressor implements a plain stochastic gradient descent learning routine which supports different 
# loss functions and penalties to fit linear regression models. SGDRegressor is well suited for regression problems 
# with a large number of training samples (> 10.000), for other problems we recommend Ridge, Lasso, or ElasticNet.


# Given a set of training examples where and (for classification), 
# our goal is to learn a linear scoring function with model parameters 
# and intercept . In order to make predictions for binary classification, 
# we simply look at the sign of . To find the model parameters, we minimize 
# the regularized training error

# where L is a loss function that measures model (mis)fit and  is a regularization term (aka penalty) that
# penalizes model complexity; alpha > 0 is a non-negative hyperparameter that controls the regularization strength.
# Log: equivalent to Logistic Regression.



# SGDClassifier(loss='hinge', *, penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, max_iter=1000, 
#               tol=0.001, shuffle=True, verbose=0, epsilon=0.1, n_jobs=None, random_state=None, 
#               learning_rate='optimal', eta0=0.0, power_t=0.5, early_stopping=False, validation_fraction=0.1, 
#               n_iter_no_change=5, class_weight=None, warm_start=False, average=False)

# SGDRegressor(loss='squared_error', *, penalty='l2', alpha=0.0001, l1_ratio=0.15, fit_intercept=True, 
#              max_iter=1000, tol=0.001, shuffle=True, verbose=0, epsilon=0.1, random_state=None, 
#              learning_rate='invscaling', eta0=0.01, power_t=0.25, early_stopping=False, validation_fraction=0.1, 
#              n_iter_no_change=5, warm_start=False, average=False)